import { EnigmaReflectorConfiguration } from "./EnigmaReflector";
import { EnigmaRotorConfiguration } from "./EnigmaRotor";

export const DEFAULT_DICTIONARY = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export const ROTOR_I: Array<EnigmaRotorConfiguration> = [
  { input: 0, output: 4 },
  { input: 1, output: 10 },
  { input: 2, output: 12 },
  { input: 3, output: 5 },
  { input: 4, output: 11 },
  { input: 5, output: 6 },
  { input: 6, output: 3 },
  { input: 7, output: 16 },
  { input: 8, output: 21 },
  { input: 9, output: 25 },
  { input: 10, output: 13 },
  { input: 11, output: 19 },
  { input: 12, output: 14 },
  { input: 13, output: 22 },
  { input: 14, output: 24 },
  { input: 15, output: 7 },
  { input: 16, output: 23, turnOver: true },
  { input: 17, output: 20 },
  { input: 18, output: 18 },
  { input: 19, output: 15 },
  { input: 20, output: 0 },
  { input: 21, output: 8 },
  { input: 22, output: 1 },
  { input: 23, output: 17 },
  { input: 24, output: 2 },
  { input: 25, output: 9 },
];

export const ROTOR_II: Array<EnigmaRotorConfiguration> = [
  { input: 0, output: 0 },
  { input: 1, output: 9 },
  { input: 2, output: 3 },
  { input: 3, output: 10 },
  { input: 4, output: 18, turnOver: true },
  { input: 5, output: 8 },
  { input: 6, output: 17 },
  { input: 7, output: 20 },
  { input: 8, output: 23 },
  { input: 9, output: 1 },
  { input: 10, output: 11 },
  { input: 11, output: 7 },
  { input: 12, output: 22 },
  { input: 13, output: 19 },
  { input: 14, output: 12 },
  { input: 15, output: 2 },
  { input: 16, output: 16 },
  { input: 17, output: 6 },
  { input: 18, output: 25 },
  { input: 19, output: 13 },
  { input: 20, output: 15 },
  { input: 21, output: 24 },
  { input: 22, output: 5 },
  { input: 23, output: 21 },
  { input: 24, output: 14 },
  { input: 25, output: 4 },
];

export const ROTOR_III: Array<EnigmaRotorConfiguration> = [
  { input: 0, output: 1 },
  { input: 1, output: 3 },
  { input: 2, output: 5 },
  { input: 3, output: 7 },
  { input: 4, output: 9 },
  { input: 5, output: 11 },
  { input: 6, output: 2 },
  { input: 7, output: 15 },
  { input: 8, output: 17 },
  { input: 9, output: 19 },
  { input: 10, output: 23 },
  { input: 11, output: 21 },
  { input: 12, output: 25 },
  { input: 13, output: 13 },
  { input: 14, output: 24 },
  { input: 15, output: 4 },
  { input: 16, output: 8 },
  { input: 17, output: 22 },
  { input: 18, output: 6 },
  { input: 19, output: 0 },
  { input: 20, output: 10 },
  { input: 21, output: 12, turnOver: true },
  { input: 22, output: 20 },
  { input: 23, output: 18 },
  { input: 24, output: 16 },
  { input: 25, output: 14 },
];

export const ROTOR_IV: Array<EnigmaRotorConfiguration> = [
  { input: 0, output: 4 },
  { input: 1, output: 18 },
  { input: 2, output: 14 },
  { input: 3, output: 21 },
  { input: 4, output: 15 },
  { input: 5, output: 25 },
  { input: 6, output: 9 },
  { input: 7, output: 0 },
  { input: 8, output: 24 },
  { input: 9, output: 16, turnOver: true },
  { input: 10, output: 20 },
  { input: 11, output: 8 },
  { input: 12, output: 17 },
  { input: 13, output: 7 },
  { input: 14, output: 23 },
  { input: 15, output: 11 },
  { input: 16, output: 13 },
  { input: 17, output: 5 },
  { input: 18, output: 19 },
  { input: 19, output: 6 },
  { input: 20, output: 10 },
  { input: 21, output: 3 },
  { input: 22, output: 2 },
  { input: 23, output: 12 },
  { input: 24, output: 22 },
  { input: 25, output: 1 },
];

export const ROTOR_V: Array<EnigmaRotorConfiguration> = [
  { input: 0, output: 21 },
  { input: 1, output: 25 },
  { input: 2, output: 1 },
  { input: 3, output: 17 },
  { input: 4, output: 6 },
  { input: 5, output: 8 },
  { input: 6, output: 19 },
  { input: 7, output: 24 },
  { input: 8, output: 20 },
  { input: 9, output: 15 },
  { input: 10, output: 18 },
  { input: 11, output: 3 },
  { input: 12, output: 13 },
  { input: 13, output: 7 },
  { input: 14, output: 11 },
  { input: 15, output: 23 },
  { input: 16, output: 0 },
  { input: 17, output: 22 },
  { input: 18, output: 12 },
  { input: 19, output: 9 },
  { input: 20, output: 16 },
  { input: 21, output: 14 },
  { input: 22, output: 5 },
  { input: 23, output: 4 },
  { input: 24, output: 2 },
  { input: 25, output: 10, turnOver: true },
];

export const REFLECTOR_A: Array<EnigmaReflectorConfiguration> = [
  { input: 0, output: 4 },
  { input: 1, output: 9 },
  { input: 2, output: 12 },
  { input: 3, output: 25 },
  { input: 4, output: 0 },
  { input: 5, output: 11 },
  { input: 6, output: 24 },
  { input: 7, output: 23 },
  { input: 8, output: 21 },
  { input: 9, output: 1 },
  { input: 10, output: 22 },
  { input: 11, output: 5 },
  { input: 12, output: 2 },
  { input: 13, output: 17 },
  { input: 14, output: 16 },
  { input: 15, output: 20 },
  { input: 16, output: 14 },
  { input: 17, output: 13 },
  { input: 18, output: 19 },
  { input: 19, output: 18 },
  { input: 20, output: 15 },
  { input: 21, output: 8 },
  { input: 22, output: 10 },
  { input: 23, output: 7 },
  { input: 24, output: 6 },
  { input: 25, output: 3 },
];

export const REFLECTOR_B: Array<EnigmaReflectorConfiguration> = [
  { input: 0, output: 24 },
  { input: 1, output: 17 },
  { input: 2, output: 20 },
  { input: 3, output: 7 },
  { input: 4, output: 16 },
  { input: 5, output: 18 },
  { input: 6, output: 11 },
  { input: 7, output: 3 },
  { input: 8, output: 15 },
  { input: 9, output: 23 },
  { input: 10, output: 13 },
  { input: 11, output: 6 },
  { input: 12, output: 14 },
  { input: 13, output: 10 },
  { input: 14, output: 12 },
  { input: 15, output: 8 },
  { input: 16, output: 4 },
  { input: 17, output: 1 },
  { input: 18, output: 5 },
  { input: 19, output: 25 },
  { input: 20, output: 2 },
  { input: 21, output: 22 },
  { input: 22, output: 21 },
  { input: 23, output: 9 },
  { input: 24, output: 0 },
  { input: 25, output: 19 },
];

export const REFLECTOR_C: Array<EnigmaReflectorConfiguration> = [
  { input: 0, output: 5 },
  { input: 1, output: 21 },
  { input: 2, output: 15 },
  { input: 3, output: 9 },
  { input: 4, output: 8 },
  { input: 5, output: 0 },
  { input: 6, output: 14 },
  { input: 7, output: 24 },
  { input: 8, output: 4 },
  { input: 9, output: 3 },
  { input: 10, output: 17 },
  { input: 11, output: 25 },
  { input: 12, output: 23 },
  { input: 13, output: 22 },
  { input: 14, output: 6 },
  { input: 15, output: 2 },
  { input: 16, output: 19 },
  { input: 17, output: 10 },
  { input: 18, output: 20 },
  { input: 19, output: 16 },
  { input: 20, output: 18 },
  { input: 21, output: 1 },
  { input: 22, output: 13 },
  { input: 23, output: 12 },
  { input: 24, output: 7 },
  { input: 25, output: 11 },
];

export const ROTOR_I_DICTIONARY = "EKMFLGDQVZNTOWYHXUSPAIBRCJ";
export const ROTOR_II_DICTIONARY = "AJDKSIRUXBLHWTMCQGZNPYFVOE";
export const ROTOR_III_DICTIONARY = "BDFHJLCPRTXVZNYEIWGAKMUSQO";
export const ROTOR_IV_DICTIONARY = "ESOVPZJAYQUIRHXLNFTGKDCMWB";
export const ROTOR_V_DICTIONARY = "VZBRGITYUPSDNHLXAWMJQOFECK";

export const REFLECTOR_A_DICTIONARY = "EJMZALYXVBWFCRQUONTSPIKHGD";
export const REFLECTOR_B_DICTIONARY = "YRUHQSLDPXNGOKMIEBFZCWVJAT";
export const REFLECTOR_C_DICTIONARY = "FVPJIAOYEDRZXWGCTKUQSBNMHL";
